version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: time-tracker-ins
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080